### ISSUE TITLE
l:dictionary Grows Every Time I Reload .cmake File

### ISSUE THREAD

**Issue by umitkablan** [ujihisa/ft-cmake#1]
Hi @ujihisa,

Thanks for this ft-plugin! I accidentally found out that every time I reload cmake file ft-cmake/ftplugin/cmake.vim appends to l:dictionary - I can see it with `:set dictionary?` command.

It resolves if you change stridx function parameter to plain 'cmake.txt' but I wonder why you didn't check existence of whole s:cmake_dict instead.

Could you fix?

**Comment by ujihisa** [comment]
Thanks for your report! I didn't do probably because I wasn't smart enough in 2013 when I wrote this script :D 

Fixed at 09028f0d09f3defb2c4b17da8b5bdba52966549c and confirmed that it won't grow &l:dictionary.

The current code is overly complicated; it could be rewritten with using `setlocal dictionary^=something` but as the current code works as we want I just leave it for now.

**Comment by umitkablan** [comment]
Thanks for the fix!
Do you have a reason not to check existence of the whole path? I thought, that way it won't disturb people with same-name cmake dictionary.
